name: google_oauth2_client
version: 0.4.2
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevmoo@google.com>
description: Library to use for Google OAuth2 authentication / Client-side flow
homepage: https://github.com/dart-gde/dart-google-oauth2-library
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  crypto: '>=1.0.0 <3.0.0'
  http: '>=0.9.0 <=1.0.1'
  oauth2: '>=0.9.0 <1.0.2'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  hop: '>=0.30.3 <0.32.0'
